name: Sync Coding

on:
  push:
    branches: 
    - master
    - dev
  # pull_request:
  #   branches: [ master ]
  release:
    types: [ published ]

jobs:
  master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Run Curl
        run: |
          curl -u ${{ secrets.CODING_TOKEN_API }} \
             -v -X POST  'https://volantis-x.coding.net/api/cci/job/387490/trigger' \
             -H 'Content-Type: application/json' \
             -d '
              {
                "envs": [
                  {
                    "name": "BRANCH",
                    "value": "master",
                    "sensitive": 0
                  }
                ]
              }'
  dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Run Curl
        run: |
          curl -u ${{ secrets.CODING_TOKEN_API }} \
             -v -X POST  'https://volantis-x.coding.net/api/cci/job/387490/trigger' \
             -H 'Content-Type: application/json' \
             -d '
              {
                "envs": [
                  {
                    "name": "BRANCH",
                    "value": "dev",
                    "sensitive": 0
                  }
                ]
              }'
